### ISSUE TITLE
privateKey import Sparrow

### ISSUE THREAD

**Issue by rgray00** [DerekYeung/ordinalswallet-exporter#1]
Is it possible to import the generated privateKey to Sparrow. Is this the bip 32 master key?

**Comment by kadirbelkuyu** [comment]
Yes, it's possible to import a private key into Sparrow, but whether or not it's a BIP 32 master key depends on how it was generated. If the private key was generated using a BIP 32-compatible tool or library and followed the BIP 32 specification, then it should be a BIP 32 master key and can be imported into Sparrow. However, it's important to verify whether the key is a BIP 32 master key before importing it into Sparrow. When importing private keys into any wallet software, it's crucial to be careful and follow the instructions carefully, as mistakes can result in loss of funds.
